const NETWORK_ERROR = 'NETWORK_ERROR';
const INTERNAL_ERROR = 'INTERNAL_ERROR';
const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
const ERROR_CLIENT_LOWER_END = 400;
const ERROR_CLIENT_HIGHER_END = 499;
const ERROR_401 = 401;
const ERROR_402 = 402;
const ERROR_403 = 403;
const ERROR_404 = 404;
const ERROR_SERVER_LOWER_END = 500;
const ERROR_SERVER_HIGHER_END = 599;
const ERROR_503 = 503;
const SUCCESS_LOWER_END = 200;
const SUCCESS_HIGHER_END = 299;
const INFO_LOWER_END = 100;
const INFO_HIGER_END = 199;
const REDIRECT_LOWER_END = 300;
const REDIRECT_HIGHER_END = 399;
const ERROR_OPERATIONAL = 'OPERATIONAL';
const ERROR_NETWORK = 'NETWORK';

const ERROR_CLIENT = {
  LOWER_END: ERROR_CLIENT_LOWER_END,
  HIGHER_END: ERROR_CLIENT_HIGHER_END,
  ERROR_401,
  ERROR_402,
  ERROR_403,
  ERROR_404,
};
const ERROR_SERVER = {
  LOWER_END: ERROR_SERVER_LOWER_END,
  HIGHER_END: ERROR_SERVER_HIGHER_END,
  ERROR_503,
};
const SUCCESS = {LOWER_END: SUCCESS_LOWER_END, HIGHER_END: SUCCESS_HIGHER_END};
const INFO = {LOWER_END: INFO_LOWER_END, HIGHER_END: INFO_HIGER_END};
const REDIRECT = {
  LOWER_END: REDIRECT_LOWER_END,
  HIGHER_END: REDIRECT_HIGHER_END,
};
const NETWORK_ERRORS = {
  NETWORK_ERROR,
  INTERNAL_ERROR,
  UNKNOWN_ERROR,
};
const STATUS_CODES = {ERROR_CLIENT, ERROR_SERVER, SUCCESS, INFO, REDIRECT};
const ERROR_TYPES = {ERROR_OPERATIONAL, ERROR_NETWORK};

export {ERROR_TYPES, NETWORK_ERRORS, STATUS_CODES};
